/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package store;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.Clock;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static javax.swing.text.StyleConstants.setIcon;
import jdk.nashorn.internal.ir.BreakNode;
import sun.invoke.empty.Empty;
import sun.swing.SwingUtilities2.Section;

/**
 *
 * @author 3step for laptop
 */
public class TAMW extends javax.swing.JFrame {

    
    /**
     * 
     * Creates new form Producer
     */
    public TAMW() {
        initComponents();
        //labSugar.setText("4");
        SetIcon();
         
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lab1 = new javax.swing.JLabel();
        lab2 = new javax.swing.JLabel();
        lab3 = new javax.swing.JLabel();
        lab4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BtnSugar = new javax.swing.JButton();
        labSpagate = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labSugar = new javax.swing.JLabel();
        labOil = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        labButter = new javax.swing.JLabel();
        labID = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TAMWIN - YOUR");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lab1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lab1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/store/Images/icons8_sugar_sack_96px.png"))); // NOI18N
        lab1.setText("Sugar");

        lab2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lab2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/store/Images/spaghetti_96px.png"))); // NOI18N
        lab2.setText("Spagate");

        lab3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lab3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/store/Images/icons8_Sesame_Oil_96px.png"))); // NOI18N
        lab3.setText("Oil");

        lab4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lab4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/store/Images/icons8_butter_96px_1.png"))); // NOI18N
        lab4.setText("Butter");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("                     Quantity                                                   Quantity                                                               Quantity                                               Quantity");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("You will get one item from each category");

        BtnSugar.setBackground(new java.awt.Color(255, 197, 91));
        BtnSugar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BtnSugar.setText("Get");
        BtnSugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSugarActionPerformed(evt);
            }
        });

        labSpagate.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        labSpagate.setText("5");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Identification Number");

        labSugar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labSugar.setText("5");

        labOil.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        labOil.setText("5");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("                    commodity                                              commodity                                                       commodity                                           commodity                   ");

        labButter.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        labButter.setText("5");

        labID.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        labID.setText("5");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lab1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(labOil, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(lab2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(79, 79, 79)
                                .addComponent(lab3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(79, 79, 79))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(labButter, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labSugar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(123, 123, 123))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(431, 431, 431)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lab4, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(labSpagate, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(138, 138, 138))))
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1054, Short.MAX_VALUE)
                .addGap(79, 79, 79))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(BtnSugar, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labID, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(234, 234, 234))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(197, 197, 197))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lab4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lab2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lab1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labButter, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labSugar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labSpagate, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labOil, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(140, 192, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labID, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnSugar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(118, 118, 118))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  //  Function to decrement numbers
    public int decrement(int num){
        num = num - 1;
        return num;
        
    }
    
    
    //   Function to convert text into numbers
    public int str_To_int(String text){
        int temp = Integer.parseInt(text);
        return temp;
        
    }
    
    //  Function to convert numbers into text
    public String int_To_str(int num ){
        String temp = Integer.toString(num);
        return temp;
        
    }
          
    
    
    private void BtnSugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSugarActionPerformed

        if(BtnSugar.getText()=="Get"){
        // convert text lable to interger number 
            int numSuger =str_To_int(labSugar.getText());
            int numButter =str_To_int(labButter.getText());
            int numOil =str_To_int(labOil.getText());
            int numSpagete =str_To_int(labSpagate.getText());
         
        // Decrement the number of the goods    
            
            int num1 = decrement(numSuger);
            int num2 = decrement(numButter);
            int num3 = decrement(numOil);
            int num4 = decrement(numSpagete);
            
         // If the products are sold out   
            if(num1 == -1)
            {
                
              // Enter a zero value until the products arrive
                int temp=0;
                String text=int_To_str(temp);
                labSugar.setText(text);
                labButter.setText(text);
                labOil.setText(text);
                labSpagate.setText(text);
                
                 BtnSugar.setEnabled(false);
                //Send a waiting message to the user
                JOptionPane.showMessageDialog(null," Please wait 5 seconds for the goods to arrive");
                try {
                    Thread.sleep(5000);
                } catch (InterruptedException ex) {
                    Logger.getLogger(TAMW.class.getName()).log(Level.SEVERE, null, ex);
                }
                JOptionPane.showMessageDialog(null," Now you can get what you want");
                int temp1=5;
                String text1=int_To_str(temp1);
                labSugar.setText(text1);
                labButter.setText(text1);
                labOil.setText(text1);
                labSpagate.setText(text1);
                BtnSugar.setEnabled(true);
                
                
                
                

            
            }
            
          //Otherwise, decrease the quantity and reset it 
            else
                
            {
                String text1=int_To_str(num1);
                labSugar.setText(text1);
                labButter.setText(text1);
                labOil.setText(text1);
                labSpagate.setText(text1);
                BtnSugar.setText("End");
                BtnSugar.setBackground(new Color(255,68,61));

            }
            
           
        }
        
       // Completed purchase
        else{
            int YES =JOptionPane.showConfirmDialog(this," Thank you for using our products. Have a nice day " +
             " If you want more products, click Yes, otherwise No " ,"TAMWIN-Your",JOptionPane.YES_NO_OPTION );
           
            if(JOptionPane.YES_NO_OPTION == YES ){
                   BtnSugar.setEnabled(false);
                try {
                     JOptionPane.showMessageDialog(null," Please wait 3 seconds for others to finish");
                    
                    Thread.sleep(3000);
                } catch (InterruptedException ex) {
                    Logger.getLogger(TAMW.class.getName()).log(Level.SEVERE, null, ex);
                }
                JOptionPane.showMessageDialog(null," Can now take more again");
                 BtnSugar.setEnabled(true);
                 BtnSugar.setText("Get");
                 BtnSugar.setBackground(new Color(255,197,91));
            }
            else{
                System.exit(0);
            }
            
        
        //BtnSugar.doClick(1);
        // JOptionPane.showMessageDialog(null," The allowable limit for an individual is one item per category ");
        }
       
    }//GEN-LAST:event_BtnSugarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TAMW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TAMW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TAMW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TAMW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TAMW().setVisible(true);
                
            }
              
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnSugar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lab1;
    private javax.swing.JLabel lab2;
    private javax.swing.JLabel lab3;
    private javax.swing.JLabel lab4;
    private javax.swing.JLabel labButter;
    public javax.swing.JLabel labID;
    private javax.swing.JLabel labOil;
    private javax.swing.JLabel labSpagate;
    private javax.swing.JLabel labSugar;
    // End of variables declaration//GEN-END:variables

    private String Empty() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void SetIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
        
    }

}





























